# add token and send request
GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGFuaWVsIiwiaWF0IjoxNjE2MDAyNTY0LCJleHAiOjE2MTYwMDI1OTR9.vdfjV9d43QKFgR93xIZBFZ1Xm-L7KBf-CPboY9dFP4A

###

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGFuaWVsIiwiaWF0IjoxNjE2MDM1NTc3LCJleHAiOjE2MTYwMzg1Nzd9.P4qrp9ZZ25RsxHv7PwZeyB0cXFRvrLVmui-DQMuhCkY
###

# login to get token
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Daniel",
    "password": "234567"
}