# add token and send request
GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRhbmllbGwiLCJwYXNzd29yZCI6IjQ1NiIsInRpdGxlIjoiVGl0bGUgbmV3IiwiaWF0IjoxNjE2MjQ5MDg0LCJleHAiOjE2MTYyNTA4ODR9.kMQB-XPecm5K1OuUasFOgjFTi9UaamATEhj9KPwRKMw

###

GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRhbmllbCIsInRpdGxlIjoiRGFuaWVsIGFuZCBmcmllbmRzIiwicGFzc3dvcmQiOiIxMjMxMjMiLCJpYXQiOjE2MTYyNDkyMjMsImV4cCI6MTYxNjI1MTAyM30.9RIssMwnlo6xAT2c362lG5Cx3PaOxAXK2lf4pCKVA5k
###

# login to get token
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Daniel",
    "password": "123123"
}
###

# register a new user
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "HelloMotherFucker",
    "password": "123123",
    "title": "Title new for hello"
}